param(
    [string]$Configuration = "Debug",
    [string]$Platform = "x64",
    [switch]$SkipBuild,
    [switch]$SkipRun,
    [switch]$AllowDocMismatch,
    [ValidateSet("off", "warn", "error")]
    [string]$DocRules = "warn"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"
if (Get-Variable -Name PSNativeCommandUseErrorActionPreference -ErrorAction SilentlyContinue) {
    $PSNativeCommandUseErrorActionPreference = $false
}

function Get-ChangedFiles {
    param(
        [string]$ProjectDirName
    )

    $lines = @(git status --porcelain=v1)
    $files = @()
    foreach ($line in $lines) {
        if ($line.Length -lt 4) {
            continue
        }

        $pathPart = $line.Substring(3).Trim()
        if ($pathPart -match " -> ") {
            $pathPart = ($pathPart -split " -> ")[-1]
        }

        $normalized = $pathPart -replace "\\", "/"
        $prefix = "$ProjectDirName/"
        if ($normalized.StartsWith($prefix)) {
            $normalized = $normalized.Substring($prefix.Length)
        }

        if ($normalized) {
            $files += $normalized
        }
    }

    return @($files | Sort-Object -Unique)
}

function Test-DocRules {
    param(
        [string[]]$ChangedFiles
    )

    $rules = @(
        @{
            Name = "Code changes should update STATUS.md"
            Trigger = '^(src|include)/'
            RequiredFile = "docs/STATUS.md"
        },
        @{
            Name = "SynthEngine changes should update Architecture.md"
            Trigger = '^(src/SynthEngine|include/SynthEngine)/'
            RequiredFile = "docs/Architecture.md"
        }
    )

    $violations = @()
    foreach ($rule in $rules) {
        $triggered = $ChangedFiles | Where-Object { $_ -match $rule.Trigger }
        if (-not $triggered) {
            continue
        }

        if ($ChangedFiles -contains $rule.RequiredFile) {
            continue
        }

        $violations += [PSCustomObject]@{
            Rule = $rule.Name
            RequiredFile = $rule.RequiredFile
            TriggeredBy = ($triggered -join ", ")
        }
    }

    return $violations
}

function Get-AutoArchitectureSection {
    param(
        [string]$RepoRoot
    )

    $targets = @(
        "src/SoundGenerate.cpp",
        "src/app/RunDefaults.cpp",
        "src/app/RunExecution.cpp",
        "src/app/RunSave.cpp",
        "src/app/RunStats.cpp",
        "src/midi/MIDIParser.cpp",
        "src/midi/Sequencer.cpp",
        "src/midi/MidiPipeline.cpp",
        "src/core/RenderGateway.cpp",
        "src/SynthEngine/Engine.cpp",
        "src/SynthEngine/Events.cpp",
        "src/SynthEngine/Renderer.cpp",
        "src/SynthEngine/Voices.cpp",
        "src/io/Writer.cpp",
        "include/SynthEngine/SynthEngine.h"
    )

    $lines = @()
    foreach ($rel in $targets) {
        $full = Join-Path $RepoRoot $rel
        if (Test-Path $full) {
            $item = Get-Item $full
            $lines += "- ``$rel`` (updated: $($item.LastWriteTime.ToString('yyyy-MM-dd HH:mm:ss')))"
        }
    }

    $generatedAt = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")
    $body = @(
        "### Auto Snapshot",
        "",
        "- Generated by ``scripts/check.ps1``",
        "- Generated at: $generatedAt",
        "",
        "### Core Files",
        ""
    ) + $lines

    return ($body -join "`r`n")
}

function Update-ArchitectureDoc {
    param(
        [string]$RepoRoot
    )

    $path = Join-Path $RepoRoot "docs/Architecture.md"
    $begin = "<!-- AUTO-GENERATED:BEGIN -->"
    $end = "<!-- AUTO-GENERATED:END -->"
    $section = Get-AutoArchitectureSection -RepoRoot $RepoRoot
    $block = "$begin`r`n$section`r`n$end"

    if (-not (Test-Path $path)) {
        $initial = @(
            "# Architecture",
            "",
            "## Auto-Generated",
            "",
            $block,
            ""
        ) -join "`r`n"
        Set-Content -Path $path -Value $initial -Encoding utf8
        Write-Host "docs/Architecture.md created."
        return
    }

    $content = Get-Content -Path $path -Raw
    $newContent = $content
    $pattern = '(?s)<!-- AUTO-GENERATED:BEGIN -->.*?<!-- AUTO-GENERATED:END -->'
    if ($content -match $pattern) {
        $newContent = [regex]::Replace($content, $pattern, $block)
    }
    else {
        $append = @(
            "",
            "## Auto-Generated",
            "",
            $block,
            ""
        ) -join "`r`n"
        $newContent = $content + $append
    }

    if ($newContent -ne $content) {
        Set-Content -Path $path -Value $newContent -Encoding utf8
        Write-Host "docs/Architecture.md auto-updated."
    }
}

$repoRoot = Split-Path -Parent $PSScriptRoot
Push-Location $repoRoot
try {
    Write-Host "== F-Synthesizer check =="
    Write-Host "Repo: $repoRoot"
    Write-Host "Config: $Configuration | Platform: $Platform"

    Update-ArchitectureDoc -RepoRoot $repoRoot
    & (Join-Path $PSScriptRoot "update_synth_docs.ps1")
    & (Join-Path $PSScriptRoot "update_architecture_notes.ps1")

    $projectDirName = Split-Path -Leaf $repoRoot
    $changedFiles = @(Get-ChangedFiles -ProjectDirName $projectDirName)
    if ($changedFiles.Count -eq 0) {
        Write-Host "No local changes found."
    }
    else {
        Write-Host "Changed files:"
        $changedFiles | ForEach-Object { Write-Host "  - $_" }
    }

    $violations = @()
    if ($DocRules -ne "off") {
        $violations = @(Test-DocRules -ChangedFiles $changedFiles)
    }
    if ($AllowDocMismatch -and $DocRules -eq "error") {
        Write-Warning "-AllowDocMismatch is set. Downgrading DocRules from 'error' to 'warn'."
        $DocRules = "warn"
    }

    $docCheckFailed = $false
    if ($DocRules -eq "off") {
        Write-Host "Documentation rules: OFF"
    }
    elseif ($violations.Count -gt 0) {
        Write-Warning "Documentation update rules are not satisfied."
        foreach ($v in $violations) {
            Write-Warning "Rule: $($v.Rule)"
            Write-Warning "  Required update: $($v.RequiredFile)"
            Write-Warning "  Triggered by: $($v.TriggeredBy)"
        }
        if ($DocRules -eq "error") {
            $docCheckFailed = $true
        }
    }
    else {
        Write-Host "Documentation rules: OK"
    }

    if (-not $SkipBuild) {
        $msbuild = Get-Command msbuild -ErrorAction SilentlyContinue
        if ($null -eq $msbuild) {
            Write-Warning "msbuild is not available in PATH. Build step skipped."
        }
        else {
            Write-Host "Running build..."
            & $msbuild.Source "F-Synthesizer.vcxproj" /t:Build "/p:Configuration=$Configuration;Platform=$Platform" /m /nologo
        }
    }
    else {
        Write-Host "Build step skipped by option."
    }

    if (-not $SkipRun) {
        $exePath = Join-Path $repoRoot "build\$Platform\$Configuration\F-Synthesizer.exe"
        if (-not (Test-Path $exePath)) {
            $legacyPath = Join-Path $repoRoot "$Platform\$Configuration\F-Synthesizer.exe"
            if (Test-Path $legacyPath) {
                $exePath = $legacyPath
            }
        }
        if (Test-Path $exePath) {
            Write-Host "Running executable: $exePath"
            & $exePath
        }
        else {
            Write-Warning "Executable not found: $exePath"
            Write-Warning "Run with -SkipRun or build first."
        }
    }
    else {
        Write-Host "Run step skipped by option."
    }

    if ($docCheckFailed) {
        Write-Error "Documentation check failed. Update required markdown files or run with -AllowDocMismatch."
    }

    Write-Host "Check completed."
}
finally {
    Pop-Location
}
