param(
    [string]$Configuration = "Debug",
    [string]$Platform = "x64",
    [ValidateSet("off", "warn", "error")]
    [string]$DocRules = "warn",
    [switch]$RunRuntimeSmoke
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"
if (Get-Variable -Name PSNativeCommandUseErrorActionPreference -ErrorAction SilentlyContinue) {
    $PSNativeCommandUseErrorActionPreference = $false
}

function Get-ChangedFiles {
    param(
        [string]$ProjectDirName
    )

    $lines = @(git status --porcelain=v1)
    $files = @()
    foreach ($line in $lines) {
        if ($line.Length -lt 4) {
            continue
        }

        $pathPart = $line.Substring(3).Trim()
        if ($pathPart -match " -> ") {
            $pathPart = ($pathPart -split " -> ")[-1]
        }

        $normalized = $pathPart -replace "\\", "/"
        $prefix = "$ProjectDirName/"
        if ($normalized.StartsWith($prefix)) {
            $normalized = $normalized.Substring($prefix.Length)
        }

        if ($normalized) {
            $files += $normalized
        }
    }

    return @($files | Sort-Object -Unique)
}

function Test-DocRules {
    param(
        [string[]]$ChangedFiles
    )

    $rules = @(
        @{
            Name = "Code changes should update STATUS.md"
            Trigger = '^(src|include)/'
            RequiredFile = "docs/STATUS.md"
        },
        @{
            Name = "SynthEngine changes should update Architecture.md"
            Trigger = '^(src/SynthEngine|include/SynthEngine)/'
            RequiredFile = "docs/Architecture.md"
        }
    )

    $violations = @()
    foreach ($rule in $rules) {
        $triggered = $ChangedFiles | Where-Object { $_ -match $rule.Trigger }
        if (-not $triggered) {
            continue
        }

        if ($ChangedFiles -contains $rule.RequiredFile) {
            continue
        }

        $violations += [PSCustomObject]@{
            Rule = $rule.Name
            RequiredFile = $rule.RequiredFile
            TriggeredBy = ($triggered -join ", ")
        }
    }

    return $violations
}

function Get-AutoArchitectureSection {
    param(
        [string]$RepoRoot
    )

    $targets = @(
        "src/SoundGenerate.cpp",
        "src/app/RunDefaults.cpp",
        "src/app/RunExecution.cpp",
        "src/app/RunSave.cpp",
        "src/app/RunStats.cpp",
        "src/midi/MIDIParser.cpp",
        "src/midi/Sequencer.cpp",
        "src/midi/MIDIPipeline.cpp",
        "src/core/RenderGateway.cpp",
        "src/SynthEngine/Engine.cpp",
        "src/SynthEngine/Events.cpp",
        "src/SynthEngine/Renderer.cpp",
        "src/SynthEngine/Voices.cpp",
        "src/io/Writer.cpp",
        "include/SynthEngine/SynthEngine.h"
    )

    $lines = @()
    foreach ($rel in $targets) {
        $full = Join-Path $RepoRoot $rel
        if (Test-Path $full) {
            $item = Get-Item $full
            $lines += "- ``$rel`` (updated: $($item.LastWriteTime.ToString('yyyy-MM-dd HH:mm:ss')))"
        }
    }

    $generatedAt = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")
    $body = @(
        "### Auto Snapshot",
        "",
        "- Generated by ``scripts/check.ps1``",
        "- Generated at: $generatedAt",
        "",
        "### Core Files",
        ""
    ) + $lines

    return ($body -join "`r`n")
}

function Update-ArchitectureDoc {
    param(
        [string]$RepoRoot
    )

    $path = Join-Path $RepoRoot "docs/Architecture.md"
    $begin = "<!-- AUTO-GENERATED:BEGIN -->"
    $end = "<!-- AUTO-GENERATED:END -->"
    $section = Get-AutoArchitectureSection -RepoRoot $RepoRoot
    $block = "$begin`r`n$section`r`n$end"

    if (-not (Test-Path $path)) {
        $initial = @(
            "# Architecture",
            "",
            "## Auto-Generated",
            "",
            $block,
            ""
        ) -join "`r`n"
        Set-Content -Path $path -Value $initial -Encoding utf8
        Write-Host "docs/Architecture.md created."
        return
    }

    $content = Get-Content -Path $path -Raw -Encoding UTF8
    $newContent = $content
    $pattern = '(?s)<!-- AUTO-GENERATED:BEGIN -->.*?<!-- AUTO-GENERATED:END -->'
    if ($content -match $pattern) {
        $newContent = [regex]::Replace($content, $pattern, $block)
    }
    else {
        $append = @(
            "",
            "## Auto-Generated",
            "",
            $block,
            ""
        ) -join "`r`n"
        $newContent = $content + $append
    }

    if ($newContent -ne $content) {
        [System.IO.File]::WriteAllText($path, $newContent, [System.Text.UTF8Encoding]::new($false))
        Write-Host "docs/Architecture.md auto-updated."
    }
}

function Get-MsbuildPath {
    $cmd = Get-Command msbuild -ErrorAction SilentlyContinue
    if ($null -ne $cmd) {
        return $cmd.Source
    }

    $vswhere = "C:/Program Files (x86)/Microsoft Visual Studio/Installer/vswhere.exe"
    if (Test-Path $vswhere) {
        $found = & $vswhere -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild/**/Bin/MSBuild.exe | Select-Object -First 1
        if ($found) {
            return $found
        }
    }

    $fallbacks = @(
        "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/MSBuild.exe",
        "C:/Program Files/Microsoft Visual Studio/2022/Professional/MSBuild/Current/Bin/MSBuild.exe",
        "C:/Program Files/Microsoft Visual Studio/2022/BuildTools/MSBuild/Current/Bin/MSBuild.exe"
    )
    foreach ($path in $fallbacks) {
        if (Test-Path $path) {
            return $path
        }
    }

    return $null
}

function Resolve-ExePath {
    param(
        [string]$RepoRoot,
        [string]$Platform,
        [string]$Configuration
    )

    $candidates = @(
        (Join-Path $RepoRoot "build/$Platform/$Configuration/F-Synthesizer.exe"),
        (Join-Path $RepoRoot "$Platform/$Configuration/F-Synthesizer.exe")
    )

    foreach ($candidate in $candidates) {
        if (Test-Path $candidate) {
            return $candidate
        }
    }

    return $candidates[0]
}

function Ensure-RuntimeDependencies {
    param(
        [string]$ExePath,
        [string]$Configuration
    )

    $exeDir = Split-Path -Parent $ExePath
    $glfwPath = Join-Path $exeDir "glfw3.dll"
    if (Test-Path $glfwPath) {
        return
    }

    $vcpkgRoot = "C:/vcpkg/installed/x64-windows"
    $sourceCandidates = @(
        (Join-Path $vcpkgRoot "debug/bin/glfw3.dll"),
        (Join-Path $vcpkgRoot "bin/glfw3.dll")
    )
    foreach ($src in $sourceCandidates) {
        if (Test-Path $src) {
            Copy-Item -Path $src -Destination $glfwPath -Force
            Write-Host "Runtime dependency restored: $glfwPath"
            return
        }
    }

    throw "Missing runtime dependency glfw3.dll and no vcpkg source found."
}

function Parse-RenderStats {
    param(
        [string]$Text
    )

    $line = ($Text -split "`r?`n" | Where-Object { $_ -like "*RenderStats*" } | Select-Object -Last 1)
    if (-not $line) {
        throw "RenderStats not found in command output."
    }

    if ($line -notmatch 'peak=([^ ]+) rms=([^ ]+) nonZero=([0-9]+)/([0-9]+)') {
        throw "RenderStats parse failed: $line"
    }

    return [PSCustomObject]@{
        Peak = [double]$matches[1]
        Rms = [double]$matches[2]
        NonZero = [int]$matches[3]
        Total = [int]$matches[4]
    }
}

function Parse-OutputPath {
    param(
        [string]$Text
    )

    $line = ($Text -split "`r?`n" | Where-Object { $_ -like "Output Path:*" } | Select-Object -Last 1)
    if (-not $line) {
        throw "Output Path not found in command output."
    }

    return $line.Substring("Output Path:".Length).Trim()
}

function Invoke-CLI {
    param(
        [string]$ExePath,
        [string[]]$Args
    )

    $out = & $ExePath @Args 2>&1 | Out-String
    $exitCode = $LASTEXITCODE

    return [PSCustomObject]@{
        ExitCode = $exitCode
        Output = $out
    }
}

function Invoke-PresetStats {
    param(
        [string]$ExePath,
        [string]$Preset
    )

    $result = Invoke-CLI -ExePath $ExePath -Args @("--cli", "--preset", $Preset)
    if ($result.ExitCode -ne 0) {
        throw "Preset run failed: $Preset (exit=$($result.ExitCode))"
    }

    $stats = Parse-RenderStats -Text $result.Output
    $outputPath = Parse-OutputPath -Text $result.Output
    return [PSCustomObject]@{
        Preset = $Preset
        Peak = $stats.Peak
        Rms = $stats.Rms
        NonZero = $stats.NonZero
        Total = $stats.Total
        OutputPath = $outputPath
    }
}

function Run-QuickSmoke {
    param(
        [string]$RepoRoot,
        [string]$ExePath
    )

    $smokeDir = Join-Path $RepoRoot "output/check/smoke"
    New-Item -ItemType Directory -Path $smokeDir -Force | Out-Null

    $configPath = Join-Path $smokeDir "quick_smoke.json"
    $wavPath = Join-Path $smokeDir "quick_smoke.wav"
    $midiPath = (Join-Path $RepoRoot "assets/midi/logo.mid") -replace "\\", "/"
    $wavPathNorm = ($wavPath -replace "\\", "/")

    $json = @"
{
  "midiPath": "$midiPath",
  "wavPath": "$wavPathNorm",
  "targetChannel": 0,
  "defaultWave": "saw",
  "initialSeconds": 1,
  "bits": 16,
  "sampleRate": 44100,
  "extraReleaseSec": 0.05
}
"@
    Set-Content -Path $configPath -Value $json -Encoding UTF8

    $ok = Invoke-CLI -ExePath $ExePath -Args @("--cli", "--config", $configPath)
    if ($ok.ExitCode -ne 0) {
        throw "quick_smoke render failed (exit=$($ok.ExitCode))"
    }
    $stats = Parse-RenderStats -Text $ok.Output
    if ($stats.NonZero -le 0) {
        throw "quick_smoke produced silent output"
    }
    if (-not (Test-Path $wavPath)) {
        throw "quick_smoke wav not found: $wavPath"
    }

    $ng = Invoke-CLI -ExePath $ExePath -Args @("--cli", "--config", (Join-Path $RepoRoot "config/__missing__.json"))
    if ($ng.ExitCode -eq 0) {
        throw "missing config should fail, but exited 0"
    }

    Write-Host "Quick smoke: OK (peak=$($stats.Peak), rms=$($stats.Rms), nonZero=$($stats.NonZero)/$($stats.Total))"
}

function Write-BytesFile {
    param(
        [string]$Path,
        [byte[]]$Bytes
    )

    [System.IO.File]::WriteAllBytes($Path, $Bytes)
}

function New-MIDIFileBytes {
    param(
        [byte[]]$TrackData
    )

    $header = [byte[]](
        0x4D, 0x54, 0x68, 0x64, 0x00, 0x00, 0x00, 0x06, 0x00, 0x00, 0x00, 0x01, 0x00, 0x60
    )
    $len = [uint32]$TrackData.Length
    $trackHeader = [byte[]](
        0x4D, 0x54, 0x72, 0x6B,
        [byte](($len -shr 24) -band 0xFF),
        [byte](($len -shr 16) -band 0xFF),
        [byte](($len -shr 8) -band 0xFF),
        [byte]($len -band 0xFF)
    )
    return ($header + $trackHeader + $TrackData)
}

function Parse-WavStereoMetrics {
    param(
        [string]$WavPath
    )

    if (-not (Test-Path $WavPath)) {
        throw "WAV not found: $WavPath"
    }

    $bytes = [System.IO.File]::ReadAllBytes($WavPath)
    if ($bytes.Length -lt 44) {
        throw "WAV too short: $WavPath"
    }

    $channels = [BitConverter]::ToUInt16($bytes, 22)
    $sampleRate = [BitConverter]::ToUInt32($bytes, 24)
    $bitsPerSample = [BitConverter]::ToUInt16($bytes, 34)
    if ($channels -ne 2 -or $bitsPerSample -ne 16) {
        throw "Unsupported WAV format for smoke parse (expected stereo 16-bit): ch=$channels bits=$bitsPerSample path=$WavPath"
    }

    $dataStart = 44
    $dataBytes = [BitConverter]::ToUInt32($bytes, 40)
    $maxReadableBytes = [Math]::Min([int]$dataBytes, $bytes.Length - $dataStart)
    $frameCount = [int]($maxReadableBytes / 4)
    if ($frameCount -le 0) {
        throw "WAV has no PCM frames: $WavPath"
    }

    $sumSqL = 0.0
    $sumSqR = 0.0
    $nonZeroL = 0
    $nonZeroR = 0
    for ($i = 0; $i -lt $frameCount; $i++) {
        $offset = $dataStart + ($i * 4)
        $l = [BitConverter]::ToInt16($bytes, $offset) / 32768.0
        $r = [BitConverter]::ToInt16($bytes, $offset + 2) / 32768.0
        $sumSqL += $l * $l
        $sumSqR += $r * $r
        if ([Math]::Abs($l) -gt 1e-8) { $nonZeroL++ }
        if ([Math]::Abs($r) -gt 1e-8) { $nonZeroR++ }
    }

    return [PSCustomObject]@{
        Frames = $frameCount
        SampleRate = [int]$sampleRate
        RmsL = [Math]::Sqrt($sumSqL / $frameCount)
        RmsR = [Math]::Sqrt($sumSqR / $frameCount)
        NonZeroL = $nonZeroL
        NonZeroR = $nonZeroR
    }
}

function Estimate-WavPitchHz {
    param(
        [string]$WavPath
    )

    $bytes = [System.IO.File]::ReadAllBytes($WavPath)
    if ($bytes.Length -lt 44) {
        throw "WAV too short: $WavPath"
    }

    $sampleRate = [BitConverter]::ToUInt32($bytes, 24)
    $dataStart = 44
    $dataBytes = [BitConverter]::ToUInt32($bytes, 40)
    $maxReadableBytes = [Math]::Min([int]$dataBytes, $bytes.Length - $dataStart)
    $frameCount = [int]($maxReadableBytes / 4)
    if ($frameCount -lt 2048) {
        throw "WAV too short for pitch estimate: $WavPath"
    }

    $startFrame = [Math]::Min([int]($sampleRate * 0.10), $frameCount - 2048)
    $windowFrames = [Math]::Min([int]($sampleRate * 0.25), $frameCount - $startFrame)
    if ($windowFrames -lt 1024) {
        throw "WAV window too short for pitch estimate: $WavPath"
    }

    $crossings = 0
    $prev = [BitConverter]::ToInt16($bytes, $dataStart + ($startFrame * 4)) / 32768.0
    for ($i = 1; $i -lt $windowFrames; $i++) {
        $curr = [BitConverter]::ToInt16($bytes, $dataStart + (($startFrame + $i) * 4)) / 32768.0
        if ($prev -le 0.0 -and $curr -gt 0.0) {
            $crossings++
        }
        $prev = $curr
    }

    $durationSec = $windowFrames / [double]$sampleRate
    if ($durationSec -le 0.0) {
        throw "Invalid WAV duration for pitch estimate: $WavPath"
    }
    return $crossings / $durationSec
}

function Invoke-SmokeCaseFromConfigObject {
    param(
        [string]$ExePath,
        [string]$WorkDir,
        [string]$Name,
        [hashtable]$ConfigObject
    )

    $configPath = Join-Path $WorkDir "$Name.json"
    $wavPath = Join-Path $WorkDir "$Name.wav"
    $configObject["wavPath"] = ($wavPath -replace "\\", "/")
    $configJson = $ConfigObject | ConvertTo-Json -Depth 10
    Set-Content -Path $configPath -Value $configJson -Encoding UTF8

    $result = Invoke-CLI -ExePath $ExePath -Args @("--cli", "--config", $configPath)
    if ($result.ExitCode -ne 0) {
        throw "tier2 smoke case failed: $Name (exit=$($result.ExitCode))"
    }

    $stats = Parse-RenderStats -Text $result.Output
    if ($stats.NonZero -le 0) {
        throw "tier2 smoke case produced silent output: $Name"
    }
    if (-not (Test-Path $wavPath)) {
        throw "tier2 smoke case wav missing: $wavPath"
    }

    return [PSCustomObject]@{
        Name = $Name
        WavPath = $wavPath
        Peak = $stats.Peak
        Rms = $stats.Rms
        NonZero = $stats.NonZero
        Total = $stats.Total
    }
}

function New-Tier2SmokeConfigObject {
    param(
        [string]$MidiPath,
        [double]$Pan = 0.0,
        [hashtable]$MasterEffects = $null
    )

    $cfg = [ordered]@{
        midiPath = ($MidiPath -replace "\\", "/")
        wavPath = ""
        targetChannel = 0
        defaultWave = "sine"
        initialSeconds = 2
        bits = 16
        sampleRate = 44100
        extraReleaseSec = 0.05
        channels = [ordered]@{
            "0" = [ordered]@{
                amp = 0.22
                attackSec = 0.002
                decaySec = 0.05
                sustainLevel = 0.9
                releaseSec = 0.1
                source = [ordered]@{
                    type = "waveform"
                    wave = "sine"
                }
            }
        }
        channelMix = [ordered]@{
            "0" = [ordered]@{
                mute = $false
                solo = $false
                level = 1.0
                pan = $Pan
                gain = 1.0
            }
        }
    }

    if ($null -ne $MasterEffects) {
        $cfg["masterEffects"] = $MasterEffects
    }
    return $cfg
}

function Run-Tier2RegressionSmoke {
    param(
        [string]$RepoRoot,
        [string]$ExePath
    )

    $smokeDir = Join-Path $RepoRoot "output/check/tier2_smoke"
    New-Item -ItemType Directory -Path $smokeDir -Force | Out-Null

    $noteMidiPath = Join-Path $smokeDir "tier2_note.mid"
    $noteTrack = [byte[]](0x00,0x90,0x3C,0x64, 0x60,0x80,0x3C,0x00, 0x00,0xFF,0x2F,0x00)
    Write-BytesFile -Path $noteMidiPath -Bytes (New-MIDIFileBytes -TrackData $noteTrack)

    $dryCfg = New-Tier2SmokeConfigObject -MidiPath $noteMidiPath -Pan 0.0
    $dry = Invoke-SmokeCaseFromConfigObject -ExePath $ExePath -WorkDir $smokeDir -Name "dry_center" -ConfigObject $dryCfg

    $panLeftCfg = New-Tier2SmokeConfigObject -MidiPath $noteMidiPath -Pan -1.0
    $panLeft = Invoke-SmokeCaseFromConfigObject -ExePath $ExePath -WorkDir $smokeDir -Name "pan_left" -ConfigObject $panLeftCfg
    $panLeftMetrics = Parse-WavStereoMetrics -WavPath $panLeft.WavPath
    if ($panLeftMetrics.RmsL -le 1e-6 -or $panLeftMetrics.RmsR -gt ($panLeftMetrics.RmsL * 0.05)) {
        throw "tier2 pan endpoint regression: pan=-1 did not bias to left enough (L=$($panLeftMetrics.RmsL), R=$($panLeftMetrics.RmsR))"
    }

    $panRightCfg = New-Tier2SmokeConfigObject -MidiPath $noteMidiPath -Pan 1.0
    $panRight = Invoke-SmokeCaseFromConfigObject -ExePath $ExePath -WorkDir $smokeDir -Name "pan_right" -ConfigObject $panRightCfg
    $panRightMetrics = Parse-WavStereoMetrics -WavPath $panRight.WavPath
    if ($panRightMetrics.RmsR -le 1e-6 -or $panRightMetrics.RmsL -gt ($panRightMetrics.RmsR * 0.05)) {
        throw "tier2 pan endpoint regression: pan=1 did not bias to right enough (L=$($panRightMetrics.RmsL), R=$($panRightMetrics.RmsR))"
    }

    $fxSrrCfg = New-Tier2SmokeConfigObject -MidiPath $noteMidiPath -Pan 0.0 -MasterEffects ([ordered]@{
        sampleRateReducer = [ordered]@{ ratio = 0.0 }
    })
    $fxSrr = Invoke-SmokeCaseFromConfigObject -ExePath $ExePath -WorkDir $smokeDir -Name "fx_srr_min" -ConfigObject $fxSrrCfg
    if ([Math]::Abs($fxSrr.Rms - $dry.Rms) -lt 1e-4) {
        throw "tier2 effect endpoint regression: sampleRateReducer(ratio=0.0) changed too little against dry"
    }

    $fxBitCfg = New-Tier2SmokeConfigObject -MidiPath $noteMidiPath -Pan 0.0 -MasterEffects ([ordered]@{
        bitCrusher = [ordered]@{ bits = 1 }
    })
    $fxBit = Invoke-SmokeCaseFromConfigObject -ExePath $ExePath -WorkDir $smokeDir -Name "fx_bitcrusher_min" -ConfigObject $fxBitCfg
    if ([Math]::Abs($fxBit.Rms - $dry.Rms) -lt 1e-4) {
        throw "tier2 effect endpoint regression: bitCrusher(bits=1) changed too little against dry"
    }

    $fxFlangerCfg = New-Tier2SmokeConfigObject -MidiPath $noteMidiPath -Pan 0.0 -MasterEffects ([ordered]@{
        flanger = [ordered]@{
            enabled = $true
            mix = 1.0
            baseDelayMs = 0.1
            depthMs = 5.0
            rateHz = 8.0
            feedback = 0.95
        }
    })
    $fxFlanger = Invoke-SmokeCaseFromConfigObject -ExePath $ExePath -WorkDir $smokeDir -Name "fx_flanger_extreme" -ConfigObject $fxFlangerCfg
    if ([Math]::Abs($fxFlanger.Rms - $dry.Rms) -lt 1e-4) {
        throw "tier2 effect endpoint regression: flanger(extreme) changed too little against dry"
    }

    $rpnCenterMidiPath = Join-Path $smokeDir "rpn_center.mid"
    $rpnPlusMidiPath = Join-Path $smokeDir "rpn_plus12.mid"
    $rpnMinusMidiPath = Join-Path $smokeDir "rpn_minus12.mid"
    $rpnSetup = [byte[]](0x00,0xB0,0x65,0x00, 0x00,0xB0,0x64,0x00, 0x00,0xB0,0x06,0x0C, 0x00,0xB0,0x26,0x00)
    $noteBody = [byte[]](0x00,0x90,0x3C,0x64, 0x60,0x80,0x3C,0x00, 0x00,0xFF,0x2F,0x00)
    Write-BytesFile -Path $rpnCenterMidiPath -Bytes (New-MIDIFileBytes -TrackData ([byte[]]($rpnSetup + [byte[]](0x00,0xE0,0x00,0x40) + $noteBody)))
    Write-BytesFile -Path $rpnPlusMidiPath -Bytes (New-MIDIFileBytes -TrackData ([byte[]]($rpnSetup + [byte[]](0x00,0xE0,0x7F,0x7F) + $noteBody)))
    Write-BytesFile -Path $rpnMinusMidiPath -Bytes (New-MIDIFileBytes -TrackData ([byte[]]($rpnSetup + [byte[]](0x00,0xE0,0x00,0x00) + $noteBody)))

    $rpnCenter = Invoke-SmokeCaseFromConfigObject -ExePath $ExePath -WorkDir $smokeDir -Name "rpn_center" -ConfigObject (New-Tier2SmokeConfigObject -MidiPath $rpnCenterMidiPath -Pan 0.0)
    $rpnPlus = Invoke-SmokeCaseFromConfigObject -ExePath $ExePath -WorkDir $smokeDir -Name "rpn_plus12" -ConfigObject (New-Tier2SmokeConfigObject -MidiPath $rpnPlusMidiPath -Pan 0.0)
    $rpnMinus = Invoke-SmokeCaseFromConfigObject -ExePath $ExePath -WorkDir $smokeDir -Name "rpn_minus12" -ConfigObject (New-Tier2SmokeConfigObject -MidiPath $rpnMinusMidiPath -Pan 0.0)

    $hzCenter = Estimate-WavPitchHz -WavPath $rpnCenter.WavPath
    $hzPlus = Estimate-WavPitchHz -WavPath $rpnPlus.WavPath
    $hzMinus = Estimate-WavPitchHz -WavPath $rpnMinus.WavPath
    if ($hzPlus -lt ($hzCenter * 1.7)) {
        throw "tier2 RPN regression: +12 bend too small (centerHz=$hzCenter plusHz=$hzPlus)"
    }
    if ($hzMinus -gt ($hzCenter * 0.65)) {
        throw "tier2 RPN regression: -12 bend too small (centerHz=$hzCenter minusHz=$hzMinus)"
    }
    if ($hzPlus -lt ($hzMinus * 2.5)) {
        throw "tier2 RPN regression: +/-12 separation too small (minusHz=$hzMinus plusHz=$hzPlus)"
    }

    Write-Host ("Tier2 regression smoke: OK " +
        "(panL=[L:{0:N6},R:{1:N6}] panR=[L:{2:N6},R:{3:N6}] " +
        "fxDelta=[SRR:{4:N6},Bit:{5:N6},Flanger:{6:N6}] " +
        "rpnHz=[-12:{7:N2},0:{8:N2},+12:{9:N2}])" -f
        $panLeftMetrics.RmsL, $panLeftMetrics.RmsR,
        $panRightMetrics.RmsL, $panRightMetrics.RmsR,
        [Math]::Abs($fxSrr.Rms - $dry.Rms),
        [Math]::Abs($fxBit.Rms - $dry.Rms),
        [Math]::Abs($fxFlanger.Rms - $dry.Rms),
        $hzMinus, $hzCenter, $hzPlus)
}

function Invoke-GuiLaunchSmoke {
    param(
        [string]$ExePath,
        [string[]]$Args,
        [string]$Label
    )

    Write-Host "GUI smoke: $Label"
    $p = $null
    if ($null -eq $Args -or $Args.Count -eq 0) {
        $p = Start-Process -FilePath $ExePath -PassThru
    }
    else {
        $p = Start-Process -FilePath $ExePath -ArgumentList $Args -PassThru
    }

    Start-Sleep -Seconds 2
    if (-not $p.HasExited) {
        Stop-Process -Id $p.Id -Force
        return
    }

    throw "GUI process exited unexpectedly with code $($p.ExitCode)"
}

function Copy-ExecutableSnapshot {
    param(
        [string]$ExePath,
        [string]$SnapshotDir
    )

    if (-not (Test-Path $ExePath)) {
        return $null
    }

    if (Test-Path $SnapshotDir) {
        Remove-Item -Path $SnapshotDir -Recurse -Force -ErrorAction SilentlyContinue
    }
    New-Item -ItemType Directory -Path $SnapshotDir -Force | Out-Null

    $srcDir = Split-Path -Parent $ExePath
    Copy-Item -Path $ExePath -Destination (Join-Path $SnapshotDir "F-Synthesizer.exe") -Force
    Get-ChildItem -Path $srcDir -Filter *.dll -File | ForEach-Object {
        Copy-Item -Path $_.FullName -Destination (Join-Path $SnapshotDir $_.Name) -Force
    }

    return (Join-Path $SnapshotDir "F-Synthesizer.exe")
}

function Compare-Stats {
    param(
        [string]$Name,
        [pscustomobject]$Before,
        [pscustomobject]$After,
        [double]$PeakTolerance,
        [double]$RmsTolerance
    )

    $deltaPeak = $After.Peak - $Before.Peak
    $deltaRms = $After.Rms - $Before.Rms
    $peakChanged = [math]::Abs($deltaPeak) -gt $PeakTolerance
    $rmsChanged = [math]::Abs($deltaRms) -gt $RmsTolerance
    $newClipRisk = ($Before.Peak -le 1.0 -and $After.Peak -gt 1.0)

    Write-Host "AB($Name): before(peak=$($Before.Peak),rms=$($Before.Rms)) -> after(peak=$($After.Peak),rms=$($After.Rms))"
    Write-Host "AB($Name): deltaPeak=$deltaPeak deltaRms=$deltaRms"

    return [PSCustomObject]@{
        Name = $Name
        DeltaPeak = $deltaPeak
        DeltaRms = $deltaRms
        Passed = (-not $peakChanged) -and (-not $rmsChanged) -and (-not $newClipRisk)
        PeakChanged = $peakChanged
        RmsChanged = $rmsChanged
        NewClipRisk = $newClipRisk
    }
}

$repoRoot = Split-Path -Parent $PSScriptRoot
Push-Location $repoRoot
try {
    Write-Host "== F-Synthesizer check =="
    Write-Host "Repo: $repoRoot"
    Write-Host "Config: $Configuration | Platform: $Platform"

    Update-ArchitectureDoc -RepoRoot $repoRoot

    $projectDirName = Split-Path -Leaf $repoRoot
    $changedFiles = @(Get-ChangedFiles -ProjectDirName $projectDirName)
    if ($changedFiles.Count -eq 0) {
        Write-Host "No local changes found."
    }
    else {
        Write-Host "Changed files:"
        $changedFiles | ForEach-Object { Write-Host "  - $_" }
    }

    $docCheckFailed = $false
    if ($DocRules -ne "off") {
        $violations = @(Test-DocRules -ChangedFiles $changedFiles)
        if ($violations.Count -gt 0) {
            Write-Warning "Documentation update rules are not satisfied."
            foreach ($v in $violations) {
                Write-Warning "Rule: $($v.Rule)"
                Write-Warning "  Required update: $($v.RequiredFile)"
                Write-Warning "  Triggered by: $($v.TriggeredBy)"
            }
            if ($DocRules -eq "error") {
                $docCheckFailed = $true
            }
        }
        else {
            Write-Host "Documentation rules: OK"
        }
    }
    else {
        Write-Host "Documentation rules: OFF"
    }

    $docsOnly = ($changedFiles.Count -gt 0) -and -not ($changedFiles | Where-Object { $_ -notmatch '^(docs|docs-archive)/' })
    $compileChanged = $false
    $renderChanged = $false
    $guiChanged = $false
    $midiChanged = $false
    if ($changedFiles.Count -gt 0) {
        $compileChanged = [bool]($changedFiles | Where-Object { $_ -match '^(src|include)/|^F-Synthesizer\.vcxproj$|^F-Synthesizer\.sln$' })
        $renderChanged = [bool]($changedFiles | Where-Object { $_ -match '^(src/SynthEngine|include/SynthEngine|src/synth|include/synth)/' })
        $guiChanged = [bool]($changedFiles | Where-Object { $_ -match '^(src/gui|include/gui)/' })
        $midiChanged = [bool]($changedFiles | Where-Object { $_ -match '^(src/midi|include/midi)/' })
    }

    Write-Host "Auto plan: docsOnly=$docsOnly compileChanged=$compileChanged renderChanged=$renderChanged guiChanged=$guiChanged midiChanged=$midiChanged"

    if ($compileChanged -and -not $docsOnly) {
        $msbuildPath = Get-MsbuildPath
        if (-not $msbuildPath) {
            throw "MSBuild not found. Install Visual Studio Build Tools or add MSBuild to PATH."
        }

        Write-Host "Running build..."
        & $msbuildPath "F-Synthesizer.vcxproj" /t:Build "/p:Configuration=$Configuration;Platform=$Platform" /m /nologo
    }
    else {
        Write-Host "Build skipped (no compile-target changes)."
    }

    if ($RunRuntimeSmoke) {
        $exePath = Resolve-ExePath -RepoRoot $repoRoot -Platform $Platform -Configuration $Configuration
        if (Test-Path $exePath) {
            Ensure-RuntimeDependencies -ExePath $exePath -Configuration $Configuration
            Run-QuickSmoke -RepoRoot $repoRoot -ExePath $exePath
            Run-Tier2RegressionSmoke -RepoRoot $repoRoot -ExePath $exePath
        }
        else {
            Write-Host "Runtime smoke: skipped (executable not found: $exePath)"
        }
    }
    else {
        Write-Host "Runtime smoke: skipped (build-only mode, use -RunRuntimeSmoke to enable)"
    }

    if ($docCheckFailed) {
        throw "Documentation check failed."
    }

    Write-Host "Check completed."
}
finally {
    Pop-Location
}
