param()

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Get-AutoPlaybookSection {
    param(
        [string]$RepoRoot
    )

    $targets = @(
        "include/SynthEngine/SynthEngine.h",
        "include/SynthEngine/Filter.h",
        "include/SynthEngine/Modulation.h",
        "src/SynthEngine/Filter.cpp",
        "src/SynthEngine/Modulation.cpp",
        "src/SynthEngine/Renderer.cpp",
        "src/SynthEngine/Voices.cpp",
        "src/config/ConfigLoad.cpp",
        "src/config/ConfigJsonUtils.cpp",
        "src/gui/GUIChannelEditor.cpp",
        "src/gui/GUIConfigUtils.cpp"
    )

    $lines = @()
    foreach ($rel in $targets) {
        $full = Join-Path $RepoRoot $rel
        if (Test-Path $full) {
            $item = Get-Item $full
            $lines += "- ``$rel`` (updated: $($item.LastWriteTime.ToString('yyyy-MM-dd HH:mm:ss')))"
        }
    }

    $generatedAt = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")
    $body = @(
        "### Auto Snapshot",
        "",
        "- Generated by ``scripts/update_synth_docs.ps1``",
        "- Generated at: $generatedAt",
        "",
        "### Foundation Files",
        ""
    ) + $lines

    return ($body -join "`r`n")
}

function Update-Playbook {
    param(
        [string]$RepoRoot
    )

    $path = Join-Path $RepoRoot "docs/synth-methods/integration-playbook.md"
    $begin = "<!-- AUTO-GENERATED:BEGIN -->"
    $end = "<!-- AUTO-GENERATED:END -->"
    $section = Get-AutoPlaybookSection -RepoRoot $RepoRoot
    $block = "$begin`r`n$section`r`n$end"

    if (-not (Test-Path $path)) {
        $initial = @(
            "# 音源接続プレイブック（共通土台と方式別ガイド）",
            "",
            "## Auto-Generated",
            "",
            $block,
            ""
        ) -join "`r`n"
        Set-Content -Path $path -Value $initial -Encoding utf8
        Write-Host "docs/synth-methods/integration-playbook.md created."
        return
    }

    $content = Get-Content -Path $path -Raw -Encoding UTF8
    $newContent = $content
    $pattern = '(?s)<!-- AUTO-GENERATED:BEGIN -->.*?<!-- AUTO-GENERATED:END -->'
    if ($content -match $pattern) {
        $newContent = [regex]::Replace($content, $pattern, $block)
    }
    else {
        $append = @(
            "",
            "## Auto-Generated",
            "",
            $block,
            ""
        ) -join "`r`n"
        $newContent = $content + $append
    }

    if ($newContent -ne $content) {
        [System.IO.File]::WriteAllText($path, $newContent, [System.Text.UTF8Encoding]::new($false))
        Write-Host "docs/synth-methods/integration-playbook.md auto-updated."
    }
}

$repoRoot = Split-Path -Parent $PSScriptRoot
Push-Location $repoRoot
try {
    Update-Playbook -RepoRoot $repoRoot
}
finally {
    Pop-Location
}
